language: python

python:
      - "2.7"
      - "3.2"
      - "3.4"


before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq libjpeg-dev

# command to install dependencies
install:
    - pip install -r requirements.txt --use-mirrors
    - echo $PYTHONPATH

# command to run tests
script:
    - make test


# script: python tests/test_all_of_the_units.py
branches:
    only:
        - master

#before_script:
#    - mongo hp --eval 'db.addUser("travis", "test");'

#services:
#    - mongodb
